import type { Metadata } from "next";
import { Manrope, Open_Sans, Teko } from "next/font/google";
import "./globals.css";
import Header from "./component/common/Header";
import Footer from "./component/common/Footer";
import MotionLayout from "./MotionLayout";


const geistManrope = Manrope({
  variable: "--font-geist-manrope",
  subsets: ["latin"],
});

const geistOpenSans = Open_Sans({
  variable: "--font-geist-open-sans",
  subsets: ["latin"],
});
const geistTeko = Teko({
  variable: "--font-geist-teko",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pro Painting Construction",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png", 
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistManrope.variable} ${geistTeko.variable} ${geistOpenSans.variable} antialiased`}
      >
        <Header />
        
            <MotionLayout>{children}</MotionLayout>
        <Footer />
      </body>
    </html>
  );
}
